name = "Kura"
version = "0.2.0"
keywords = ["math"]
defaultTargets = ["Kura"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "Matroid"
git = "https://github.com/apnelson1/Matroid.git"
rev = "6d2a27f31207bbd0d45f2b321c10ea1975bdc67e"

[[require]]
name = "Canonical"
scope = "chasenorman"

[[lean_lib]]
name = "Kura"