name = "Kura"
version = "0.2.0"
keywords = ["math"]
defaultTargets = ["Kura"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "LeanCopilot"
git = "https://github.com/lean-dojo/LeanCopilot.git"
rev = "main"

[[require]]
name = "Matroid"
git = "https://github.com/apnelson1/Matroid.git"
rev = "67f6b5c73a9419f5bba7871f30bade7e23e1bf13"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Kura"
moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]